---
- name: Configure Apache Webserver
  hosts: webservers
  become: yes

  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Start and enable Apache service
      service:
        name: httpd
        state: started
        enabled: true

    - name: Create index.html
      copy:
        dest: /var/www/html/index.html
        content: |
          ✅ Hello from {{ inventory_hostname }} - Apache is running 🎉<br><br>
          👩‍💻 Deepika Paneer Selvam & 👨‍💻 Steven Mathew were here!<br><br>
          <img src="cat.webp" alt="Cat" width="300"/>

    - name: Install AWS CLI
      yum:
        name: awscli
        state: present

    - name: Download cat.webp from S3
      command: >
        aws s3 cp s3://ansibleimagehttpd/cat.webp /var/www/html/cat.webp
